---

- name: "add nodesource nodejs"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -

- name: "install nodejs 13"
  become: true
  apt: 
    name: ["node.js"]
    state: latest
    update_cache: yes


- name: "install PM2 globally"
  npm: 
    name: pm2
    global: yes